#!/bin/bash

# Colors
COLOR_OFF='\033[0m'
BLUE='\033[1;34m'
RED='\033[1;31m'
ORANGE='\033[0;33m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
GREEN='\033[1;32m'

# Main menu function
main_menu() {
    echo -e "${BLUE}Select an option and press ${GREEN}[ENTER]${BLUE} to confirm:${COLOR_OFF}"
    echo -e "${GREEN}[1] ${BLUE}Create Docker network for the microservices${COLOR_OFF}"
    echo -e "${GREEN}[2] ${BLUE}Build Docker images${COLOR_OFF}"
    echo -e "${GREEN}[3] ${BLUE}Run Docker containers${COLOR_OFF}"
    echo -e "${GREEN}[4] ${BLUE}Stop Docker containers${COLOR_OFF}"
    echo -e "${GREEN}[0] ${BLUE}Exit${COLOR_OFF}"

    # Read user input
    read -p "Enter your choice: " choice

    case $choice in
        1)
            create_network
            ;;
        2)
            build_docker_images
            ;;
        3)
            run_docker_containers
            ;;
        4)
            stop_docker_containers
            ;;
        0)
            echo -e "${YELLOW}Exiting...${COLOR_OFF}"
            exit 0
            ;;
        *)
            echo -e "${RED}Invalid choice${COLOR_OFF}"
            main_menu
            ;;
    esac
}

# Create network function
create_network() {
    echo -e "${YELLOW}Creating network...${COLOR_OFF}"
    docker network create ka-network

    main_menu
}

# Build Docker images function
build_docker_images() {
    echo -e "${YELLOW}Building Reviews service...${COLOR_OFF}"
    docker build -t ka-reviews https://github.com/ITA-Super-Cool-Pals/ka-reviews.git#main

    echo -e "${YELLOW}Building Guests service...${COLOR_OFF}"
    docker build -t ka-guests https://github.com/ITA-Super-Cool-Pals/ka-guest.git#main

    echo -e "${YELLOW}Building Occupancy service...${COLOR_OFF}"
    docker build -t ka-occupancy https://github.com/ITA-Super-Cool-Pals/ka-occupancy.git#main

    echo -e "${YELLOW}Building Rooms service...${COLOR_OFF}"
    docker build -t ka-rooms https://github.com/ITA-Super-Cool-Pals/ka-rooms.git#main

    echo -e "${YELLOW}Building Bar Sales service...${COLOR_OFF}"
    docker build -t ka-bar-sales https://github.com/ITA-Super-Cool-Pals/ka-bar-sales.git#main

    echo -e "${YELLOW}Building Booking service...${COLOR_OFF}"
    docker build -t ka-bookings https://github.com/ITA-Super-Cool-Pals/ka-booking.git#main

    echo -e "${YELLOW}Building Gateway...${COLOR_OFF}"
    docker build -t ka-gateway https://github.com/ITA-Super-Cool-Pals/ka-gateway.git#main

    main_menu
}

# Run Docker containers function
run_docker_containers() {
    echo -e "${BLUE}Enter the host path you wish to mount to ${CYAN}/app/app-db${BLUE} in the container.${COLOR_OFF}"
    echo -e "${BLUE}Examples: ${CYAN}C:/myDirectory/data${BLUE} | ${CYAN}/home/kingarthur/data${COLOR_OFF}"
    read -p "Enter host path: " user_path

    if [[ -z "$user_path" ]]; then
        echo -e "${RED}Error: You must enter a valid path.${COLOR_OFF}"
        return
    fi

    echo -e "${YELLOW}Running Reviews service...${COLOR_OFF}"
    docker run --rm -d -p 5003:5000 --name ka-reviews --network ka-network -v "$user_path:/app/app-db" ka-reviews

    echo -e "${YELLOW}Running Guests service...${COLOR_OFF}"
    docker run --rm -d -p 5002:5000 --name ka-guests --network ka-network -v "$user_path:/app/app-db" ka-guests

    echo -e "${YELLOW}Running Occupancy service...${COLOR_OFF}"
    docker run --rm -d -p 5005:5000 --name ka-occupancy --network ka-network -v "$user_path:/app/app-db" ka-occupancy

    echo -e "${YELLOW}Running Rooms service...${COLOR_OFF}"
    docker run --rm -d -p 5001:5000 --name ka-rooms --network ka-network -v "$user_path:/app/app-db" ka-rooms

    echo -e "${YELLOW}Running Bar Sales service...${COLOR_OFF}"
    docker run --rm -d -p 5008:5000 --name ka-bar-sales --network ka-network -v "$user_path:/app/app-db" ka-bar-sales

    echo -e "${YELLOW}Running Booking service...${COLOR_OFF}"
    docker run --rm -d -p 5010:5000 --name ka-bookings --network ka-network -v "$user_path:/app/app-db" ka-bookings

    echo -e "${YELLOW}Running Gateway...${COLOR_OFF}"
    docker run --rm -d -p 5000:5000 --name ka-gateway --network ka-network ka-gateway

    main_menu
}

stop_docker_containers() {
    echo -e "${YELLOW}Stopping Reviews service...${COLOR_OFF}"
    docker stop ka-reviews

    echo -e "${YELLOW}Stopping Guests service...${COLOR_OFF}"
    docker stop ka-guests

    echo -e "${YELLOW}Stopping Occupancy service...${COLOR_OFF}"
    docker stop ka-occupancy

    echo -e "${YELLOW}Stopping Rooms service...${COLOR_OFF}"
    docker stop ka-rooms

    echo -e "${YELLOW}Stopping Bar Sales service...${COLOR_OFF}"
    docker stop ka-bar-sales

    echo -e "${YELLOW}Stopping Booking service...${COLOR_OFF}"
    docker stop ka-bookings

    echo -e "${YELLOW}Stopping Gateway...${COLOR_OFF}"
    docker stop ka-gateway

    main_menu
}

# Start script by displaying main menu
main_menu
